app:
  auth-service:
    registrationUrl: http://localhost:9090/oauth/users/register
    loginUrl: http://localhost:9090/oauth/token
    validateUrl: http://localhost:9090/oauth/check_token
    basicAuth: Basic bGVkZ2l0eTp0ZW1w
